- hosts: dev
  sudo: true
  vars:
    rbenv:
      env: system
      version: v0.4.0
      ruby_version: 2.1.5
  roles:
    - users
    - {role: apt-util, tags: ['apt-util']}
    - {role: apt-db,   tags: ['apt-db']}
    - rbenv
    - apt-web
