- name: 'install apt db packages'
  apt: pkg="{{item}}" state=present
  with_items:
    - mysql-server
    - python-mysqldb
  tags: mysqld

- name: set my.conf to db server
  template: src={{ my_conf_file }} dest=/etc/mysql/conf.d/charset.cnf owner=root mode=0644
  register: my_conf

- name: restart mysql
  service: name=mysql state=restarted
  when: my_conf.changed

- name: Create database
  mysql_db: db={{ dbname }} state=present encoding=utf8mb4
  tags: mysqld

- name: Create database user
  mysql_user: >-
    name={{ dbuser }}
    password="{{ dbpassword }}"
    priv={{ dbname }}.*:ALL
    state=present
  tags: mysqld

